def help(user_name):
    if user_name.upper() == "ADMIN":
        print("===============================================HELP==============================================")
        print("|  Command             |    Input    |                       Keterangan                         |")
        print("=================================================================================================")
        print("|  Register            |   reg       | melakukan registrasi user baru                           |")
        print("|  Login               |   log       | melakukan login ke dalam sistem                          |")
        print("|  Cari Rarity         |   crare     | melakukan pencarian item berdasarkan rarity              |")
        print("|  Cari Tahun          |   cyear     | melakukan pencarian item berdasarkan tahun ditemukan     |")
        print("|  Tambah              |   add       | menambahkan item ke dalam sistem                         |")
        print("|  Hapus               |   delete    | menghapus gadget/consumable dari sistem                  |")
        print("|  Ubah item           |   change    | mengubah jumlah gadget/consumable dari sistem            |")
        print("|  Riwayat Pinjam      |   hborrow   | menampilkan riwayat peminjaman gadget oleh user          |")
        print("|  Riwayat kembalian   |   hreturn   | menampilkan riwayat pengembalian gadget oleh user        |")
        print("|  Riwayat Minta       |   hdemand   | menampilkan riwayat pengambilan consumable oleh user     |")
        print("|  Save                |   save      | melakukan penyimpanan data ke dalam file                 |")
        print("|  Help                |   help      | menampilkan panduan penggunaan sistem                    |")
        print("|  Exit                |   exit      | keluar dari program                                      |")
        print("=================================================================================================")

    elif not user_name:
        print("===============================================HELP==============================================")
        print("|  Command             |    Input    |                       Keterangan                         |")
        print("=================================================================================================")
        print("|  Login               |   log       | melakukan login ke dalam sistem                          |")
        print("|  Help                |   help      | menampilkan panduan penggunaan sistem                    |")
        print("|  Exit                |   exit      | keluar dari program                                      |")
        print("=================================================================================================")

    else:
        print("===============================================HELP==============================================")
        print("|  Command             |    Input    |                       Keterangan                         |")
        print("=================================================================================================")
        print("|  Login               |   log       | melakukan login ke dalam sistem                          |")
        print("|  Cari Rarity         |   crare     | melakukan pencarian item berdasarkan rarity              |")
        print("|  Cari Tahun          |   cyear     | melakukan pencarian item berdasarkan tahun ditemukan     |")
        print("|  Pinjam              |   borrow    | melakukan peminjaman gadget dari sistem                  |")
        print("|  Kembali             |   return    | melakukan pengembalian gadget kepada sistem              |")
        print("|  Minta               |   demand    | melakukan pengambilan consumable dari sistem             |")
        print("|  Save                |   save      | melakukan penyimpanan data ke dalam file                 |")
        print("|  Help                |   help      | menampilkan panduan penggunaan sistem                    |")
        print("|  Exit                |   exit      | keluar dari program                                      |")
        print("=================================================================================================")